# Site settings
title: Blog de Son Link
email: sonlink.dourden@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mi blog personal donde hablo de mis proyectos, tutoriales, etc, ademas de exponer mis trabajos y proyectos
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://son-link.github.io" # the base hostname & protocol for your site
twitter_username: sonlink
github_username:  son-link

# Build settings
markdown: kramdown
